export enum NotificationType {
    COMMENT = 'COMMENT',
    REPLIED = 'REPLIED',
    REACTION_NEWS = 'REACTION_NEWS',
    REACTION_COMMENT = 'REACTION_COMMENT',
    FOLLOWED = 'FOLLOWED',
    NEWS_VERIFY = 'NEWS_VERIFY',
    NEWS_REJECT = 'NEWS_REJECT'
}